name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v3
      
      - name: Clone and patch
        run: make clone-and-patch

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set ENV vars
        run: |
          TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)
          echo "IMAGE_TAG"=$TAG >> $GITHUB_ENV
          echo "IMAGE_NAME_HASURA"=ghcr.io/soluchok/inigo-hs/hasura >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push container image (router)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME_HASURA }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME_HASURA }}:latest

